
Function GetSalesReportToConsignorList() Export
	Return CommissionTradeServer.__GetSalesReportToConsignorList();
EndFunction

Function GetFillingDataBySalesReportToConsignor(DocRef) Export
	Return CommissionTradeServer.__GetFillingDataBySalesReportToConsignor(DocRef);
EndFunction
