name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
  issue_comment:
    types: [created]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Add To GitHub projects
      uses: actions/add-to-project@v0.4.0
      with:
        # URL of the project to add issues to
        project-url: 'https://github.com/orgs/IRPTeam/projects/8'
        # A GitHub personal access token with write access to the project
        github-token:  ${{ secrets.GITHUB_TOKEN }}
        # A comma-separated list of labels to use as a filter for issue to be added
        #labeled: # optional
        # The behavior of the labels filter, AND to match all labels, OR to match any label, NOT to exclude any listed label (default is OR)
        #label-operator: # optional
